name: Daily Job Search

on:
  schedule:
    - cron: '0 14 * * *'  # 8 PM IST = 14:30 UTC
  workflow_dispatch:

jobs:
  job_search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install google-search-results

      - name: Run Job Finder
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_NAME: ${{ secrets.SENDER_NAME }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
          MAX_RESULTS_PER_QUERY: ${{ secrets.MAX_RESULTS_PER_QUERY }}
          DAYS_BACK_LIMIT: ${{ secrets.DAYS_BACK_LIMIT }}
          STRICT_MATCH: ${{ secrets.STRICT_MATCH }}
        run: python job_finder.py