name: Daily Job Search (20:00 IST)

- name: Install dependencies
  run: pip install -r requirements.txt

on:
  schedule:
    # 20:00 IST == 14:30 UTC
    - cron: "30 14 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run job finder
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_NAME: ${{ secrets.SENDER_NAME }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
          MAX_RESULTS_PER_QUERY: ${{ vars.MAX_RESULTS_PER_QUERY }}
          DAYS_BACK_LIMIT: ${{ vars.DAYS_BACK_LIMIT }}
          STRICT_MATCH: ${{ vars.STRICT_MATCH }}
        run: python job_finder.py