name: Daily Pune/Remote Job Search
on:
  schedule:
    - cron: '0 14 * * *'  # 8 PM IST
  workflow_dispatch:

jobs:
  job_alert:
    runs-on: ubuntu-latest
    env:
      SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      SENDER_NAME: "Job Alerts Bot"
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
      MAX_RESULTS_PER_QUERY: 20
      DAYS_BACK_LIMIT: 7
      STRICT_MATCH: false
      WORKFLOW_NAME: Pune/Remote Jobs
      JOB_LOCATIONS: Pune,Remote

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run job finder
        run: python job_finder.py